### ISSUE TITLE
Special source doesnt apply to /Statedefinition$Builder$add

### ISSUE THREAD

**Issue by hube12** [hube12/DecompilerMC#1]
`public Builder<O, S> a(Property<?> ... arrproperty) {
            for (Property<?> property : arrproperty) {
                this.validateProperty(property);
                this.properties.put(property.getName(), property);
            }
            return this;
        }`
this sould be add and not a but in tsrg i gave 
`a ([Lnet/minecraft/world/level/block/state/properties/Property;)Lbxh$a; add` but it didnt apply the name correctly and i really have no idea why, its the only case tho

**Comment by tryashtar** [comment]
Affects everything that returns or passes in non-primitive array, other examples:
`Path.getOpenSet() : Node[]`
`Path.getClosedSet() : Node[]`
`DirectionProperty.create(String, Direction[]) : DirectionProperty`
`ChunkAccess.setBiomes(Biome[])`
`ChunkAccess.getBiomes() : Biome[]`

**Comment by hube12** [comment]
fixed in latest patch
