### ISSUE TITLE
Error remapping on MacOS

### ISSUE THREAD

**Issue by ShaneBeee** [hube12/DecompilerMC#10]
So I ran the program (had some issues but based on another issue I was able to update ssl on my Mac) and I ran into this error 
```
=== Remapping jar using SpecialSource ====
ERROR: Missing files: ./lib/SpecialSource-1.8.6.jar or mappings/1.14.4/client.tsrg or versions/1.14.4/client.jar
aborting
```
same thing for doing the server:
```
=== Remapping jar using SpecialSource ====
ERROR: Missing files: ./lib/SpecialSource-1.8.6.jar or mappings/1.14.4/server.tsrg or versions/1.14.4/server.jar
Aborting
```

I can confirm that all the "missing files" are actually all there.

**Comment by ShaneBeee** [comment]
Welp, scratch that, I moved the lib folder to my main home folder and now it works!!!

**Comment by hube12** [comment]
yeah the issue when using the release without launching it from command prompt. Path aren't well set on mac

**Comment by ShaneBeee** [comment]
> yeah the issue when using the release without launching it from command prompt. Path aren't well set on mac

Duly noted. Glad I was able to figure it out.
Awesome tool btw... thank you so much for this.
