### ISSUE TITLE
Is execution coming soon?

### ISSUE THREAD

**Issue by Justsnoopy30** [hube12/DecompilerMC#11]

**Comment by Justsnoopy30** [comment]
@hube12

**Comment by hube12** [comment]
my definition of soon is probably not yours and since i dont use 1.14 that much you are better off with mcp (since they updated) or fabric. But once it is out i will be sure to ping you here...

**Comment by Multimegamander** [comment]
how do I get the new mcp?

**Comment by Justsnoopy30** [comment]
https://github.com/hypercubemc-github/Modern-Minecraft-Decompiler
