### ISSUE TITLE
Program Decompiles Dependencies

### ISSUE THREAD

**Issue by Th3T3chn0G1t** [hube12/DecompilerMC#13]
When running the program it would appear it also decompiles dependencies packaged with Minecraft such as fastutil - this obviously takes significantly longer than just decompiling Minecraft and seems somewhat unnecessary?  

I don't personally see why one would need them decompiled swell but I'm no expert - perhaps make the dependencies an option in the process?

**Comment by hube12** [comment]
Hi indeed, i will fix that, sorry for the inconvenience

**Comment by a8underscore** [comment]
I think you should make it optional

**Comment by hube12** [comment]
#20
