### ISSUE TITLE
About 1.11.2 missing json[client_mappings]

### ISSUE THREAD

**Issue by Alimo1029** [hube12/DecompilerMC#15]
Download version 1.11.2, I open 1.11.2json, and I can't this 'client_mappings'. It seems that 1.11.2 not this client_mappings, but 1.14.4 have, so could you work out this issue? thank you :)

【My English is not well】

**Comment by hube12** [comment]
Hi, the mojang mappings were introduced only at 1.14.4+ or 20w19a+. You cannot use this tool for older versions.
