### ISSUE TITLE
No source code is created when no java.exe in PATH.

### ISSUE THREAD

**Issue by Tnze** [hube12/DecompilerMC#26]
It will be good if there is even a error message.

**Comment by hube12** [comment]
print('Java JDK is not installed ! Please install java JDK from http://java.oracle.com or OpenJDK')
input("Aborting, press anything to exit")
sys.exit(1)
Those lines should trigger tho

**Comment by Tnze** [comment]
I'm using the binary package for lazy people :)
It just exit and left the `src/version/` fold empty.

**Comment by hube12** [comment]
That one is a bit old, I will update it ;)
