### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by Kloetzchengrafik** [hube12/DecompilerMC#27]
If i would publish the client (Build it) what must i do?

**Comment by Kloetzchengrafik** [comment]
and how can i run my client?

**Comment by hube12** [comment]
pip install pyinstaller pyinstaller main.py --distpath build --onefile

**Comment by Kloetzchengrafik** [comment]
...And where's my builded client xD

**Comment by Kloetzchengrafik** [comment]
In the folder build are only some weird files

**Comment by Kloetzchengrafik** [comment]
(Im on macos)

**Comment by hellogaminglike92** [comment]
its in the build folder and called main.exe
