### ISSUE TITLE
Cannot decompile version 21w19a due to Java 16

### ISSUE THREAD

**Issue by misode** [hube12/DecompilerMC#31]
![image](https://user-images.githubusercontent.com/17352009/117975786-57a1fa00-b32f-11eb-8c53-4cf47f3fdf02.png)

**Comment by hube12** [comment]
Hey, thanks for reporting, this will be handled quickly, I did not expect a snapshot to drop at 3pm

**Comment by hube12** [comment]
This has been fixed
