### ISSUE TITLE
Shebang line on main.py doesn't work with crlf line endings

### ISSUE THREAD

**Issue by dhouck** [hube12/DecompilerMC#33]
As-is, you get an `/usr/bin/env: ‘python3\r’: No such file or directory` unless you happen to have a program named python3<cr>.

**Comment by hube12** [comment]
`dos2unix main.py` should fix it and I just pushed a gitattribute and editorconfig to fix line ending on linux

**Comment by dhouck** [comment]
Thanks for the quick response!  I did `dos2unix` but didn't know if it actually made sense to push that depending on your editor situation.
