### ISSUE TITLE
Allow giving my own jar/deobfuscation maps

### ISSUE THREAD

**Issue by u9g** [hube12/DecompilerMC#36]
That way people can decompile 1.18.1 exp snap1 since the wiki has links to the deobfusc maps: https://minecraft.fandom.com/wiki/Java_Edition_1.18_Experimental_Snapshot_1#cite_note-1

**Comment by hube12** [comment]
You do know that you can enter manual mode and do that, right?

**Comment by hube12** [comment]
I litterally decompiled 1.18 exp1 5min after release

**Comment by u9g** [comment]
how did you get the deobfuscation map?

**Comment by u9g** [comment]
also how did you load the manual deobfusc map using options?

**Comment by hube12** [comment]
![S10716-23250003](https://user-images.githubusercontent.com/26262005/126010078-d28a629f-8b55-495d-aa3b-9b7073c21b26.jpg)
Everything is in the json, so download both and place them in the for instance 1.17.1 folder then don't download mappings nor jar with manual mode. Or if you want to modify the py code, remove the check for the version present in the manifest and put the .json in the version folder and use the name as the version.
