### ISSUE TITLE
"Could not load the following classes"

### ISSUE THREAD

**Issue by hornta** [hube12/DecompilerMC#37]
I'm getting some problems with classes not decompiling. Is there something I can do about that or is it just the way things are? 😄 
```
/*
 * Decompiled with CFR 0.146.
 * 
 * Could not load the following classes:
 *  com.mojang.bridge.Bridge
 *  com.mojang.bridge.game.GameSession
 *  com.mojang.bridge.game.GameVersion
 *  com.mojang.bridge.game.Language
 *  com.mojang.bridge.game.PerformanceMetrics
 *  com.mojang.bridge.game.RunningGame
 *  com.mojang.bridge.launcher.Launcher
 *  com.mojang.bridge.launcher.SessionEventListener
 *  javax.annotation.Nullable
 */
```

**Comment by hube12** [comment]
This is not a problem, those are dependencies that I didn't resolved before launching the decompilation because decompiling those makes no sense. They are librairies that mojang use that are not part of Minecraft source code. You can see all of them on github and alike.

**Comment by hornta** [comment]
Aha, can you give me any hints on where to find them? I've been going crazy because I can't find them anywhere and they are my last missing puzzle piece 😁

**Comment by hube12** [comment]
maven {

url "https://libraries.minecraft.net"

}

**Comment by hube12** [comment]
https://github.com/hube12/TemplateMC/blob/master/libs/download_libs.py

**Comment by hube12** [comment]
https://github.com/hube12/TemplateMC/blob/master/build.gradle#L19
