### ISSUE TITLE
Decompiling server broke with 21w39a

### ISSUE THREAD

**Issue by misode** [hube12/DecompilerMC#39]
As mentioned in the changelog. Only the bootstrap `Main` class is decompiled now.
![image](https://user-images.githubusercontent.com/17352009/135492817-3085c5f6-0a73-4750-9e82-36936a6e65f6.png)

**Comment by hube12** [comment]
this will be fixed in a few hour

**Comment by hube12** [comment]
> @hube12 Sorry to bother, but any updates?

Oh yeah, sorry forgot to push, here it is

**Comment by hube12** [comment]
it's really a simple fix, just parse META-INF/versions.list then go in META-INF/versions/{path} and extract that one and substitute it to the other one. (I don't care about the libs)

**Comment by misode** [comment]
@hube12 The solution is not that simple, as now the decompiler doesn't have any knowledge of the libraries, writing warnings and giving slightly different results code-wise.

The real solution probably involves using the contents of `META-INF/classpath-joined` as described in the changelog.

![image](https://user-images.githubusercontent.com/17352009/136118123-c8a05e96-6388-4c03-b640-37afb1c60de1.png)
![image](https://user-images.githubusercontent.com/17352009/136117990-db26eda5-905a-4c5d-931d-203861800699.png)

**Comment by hube12** [comment]
I mean to me both are readable but I do get where you are coming from, I will later so I can make back a full archive with the libs to give to the decompiler
