### ISSUE TITLE
Merging client and server

### ISSUE THREAD

**Issue by clabe45** [hube12/DecompilerMC#44]
I'm proposing to add an option to generate a merged sources directory containing the code for the client and server. [Yarn](https://github.com/FabricMC/stitch/blob/master/src/main/java/net/fabricmc/stitch/merge/JarMerger.java) and [Forge](https://github.com/MinecraftForge/MinecraftForge) are currently doing this - basically, the client and server jars get merged into a single jar which are then decompiled and deobfuscated.

I know I would find this feature really useful for a project I'm working on. Also, you would no longer need to decide whether to generate the client or the server when running DecompilerMC (useful for people researching across the stack). I'm guessing it would be faster to generate merged sources than generating both the client and the server individually, too.

I would be down to make a PR for this (if you're okay with Google being the copyright holder over the code I write, since I'm currently interning there).

**Comment by hube12** [comment]
Mmh, this tool was mostly designed to be used as a quick and dirty way to obtain source, it's not optimized in any way (it uses Python btw). 

For me client and server merging don't make much sense for now as long as mojang still ship an internal server for the client. But if you need that I can add a quick and dirty merging, it's litterally one more java lib and 5 lines of Python.

**Comment by clabe45** [comment]
Ahh, that's a good point. I'll just generated the client
