### ISSUE TITLE
Doesn't decompile bundled jar properly

### ISSUE THREAD

**Issue by Phoenix616** [hube12/DecompilerMC#48]
Minecraft now bundles the actual game logic inside the `META-INF/versions` folder instead of including it directly. This will only decompile the outer layer, not the actual game logic jar.

**Comment by hube12** [comment]
This does the job : https://github.com/hube12/DecompilerMC/blob/master/main.py#L203-L236

**Comment by hube12** [comment]
Please use the code repo, maybe the release is too old

**Comment by hube12** [comment]
I sucessfully decompiled 22w42a client, please give me the version failing

**Comment by Phoenix616** [comment]
I used the latest release exe and the latest snapshot. Gonna try it in a fresh foder again though, maybe some previous files/version messed something up.

**Comment by hube12** [comment]
I meant the release is not up to date the code is

**Comment by Phoenix616** [comment]
Yeah using the main.py directly seems to work. Kind of confused how the exe didn't as it's from (almost) the last commit and the last one doesn't seem to change anything there?

**Comment by hube12** [comment]
I will release a new exe, actually I will make a github action to publish that exe so it can be traced to a commit directly

**Comment by hube12** [comment]
I will however note that mojang did introduce a new behavior in their version manifest, thx for having me look
