### ISSUE TITLE
Cannot Decompile 1.20.5 Prerelease-1 due to Java 21

### ISSUE THREAD

**Issue by CowgillAlex** [hube12/DecompilerMC#54]
![image](https://github.com/hube12/DecompilerMC/assets/142602686/3fff3e1a-fcf7-49a4-bc3c-bff2aca1edf7)

This snapshot changed the version of Java used to 21, which has broken the decompiler

**Comment by hube12** [comment]
I will have to address the issue this evening then, please wait a bit for me to update

**Comment by hube12** [comment]
Fixed and published artefacts
