### ISSUE TITLE
How do you build this in IntelliJ Idea?

### ISSUE THREAD

**Issue by Justsnoopy30** [hube12/DecompilerMC#8]
How do you build this in IntelliJ Idea? I have the src/1.14.4/client set up as a project in IntelliJ Idea, how do I compile it into a jar file?

**Comment by hube12** [comment]
its not currently buildable, i didn't post the patch i made for fernflower yet, for now its only for code digging, no execution

**Comment by Justsnoopy30** [comment]
Oh ok.

**Comment by ajloveslily14** [comment]
Is there any update on buildability?

**Comment by hube12** [comment]
@ajloveslily14 It was not really a goal I wished this script to achieve. You can use fabric or mcp-reborn to do that.

**Comment by ajloveslily14** [comment]
I see. I guess I'll have to start looking into that.
